services:
  database:
    image: mysql:lts
    platform: linux/amd64 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: corpstarter
      MYSQL_USER: user
      MYSQL_PASSWORD: password
   
    volumes:
      - db_data:/var/lib/mysql
    restart: always 

  backend:
  
    image: europe-west1-docker.pkg.dev/[VOTRE_PROJET]/[VOTRE_DEPOT]/corpstarter-backend:v1
    ports:
      - "8000:80"
    depends_on:
      - database
    restart: always

  frontend:
    
    image: europe-west1-docker.pkg.dev/[VOTRE_PROJET]/[VOTRE_DEPOT]/corpstarter-frontend:v1   
    ports:
      - "80:80" 
    depends_on:
      - backend
    restart: always

volumes:
  db_data: