<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXsyFd9k\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXsyFd9k/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXsyFd9k.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXsyFd9k\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXsyFd9k\App_KernelDevDebugContainer([
    'container.build_hash' => 'XsyFd9k',
    'container.build_id' => '93630f12',
    'container.build_time' => 1774535412,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXsyFd9k');
