<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHro1Sen\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHro1Sen/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHro1Sen.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHro1Sen\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHro1Sen\App_KernelDevDebugContainer([
    'container.build_hash' => 'Hro1Sen',
    'container.build_id' => 'a25a9462',
    'container.build_time' => 1774608691,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHro1Sen');
