<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App_Entity_Project' => 0,
'App_Entity_ProjectStatus' => 1,
'App_Entity_Users' => 2,
'App_Entity_UserTypes' => 3,

], [

0 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'App\\Entity\\Project',
            ],
            'attributesMetadata' => [
                [
                    'id' => $o[1],
                    'name' => $o[2],
                    'requested_budget' => $o[3],
                    'allocated_budget' => $o[4],
                    'illustration_path' => $o[5],
                    'creation_date' => $o[6],
                    'status' => $o[7],
                    'requester' => $o[8],
                    'approver' => $o[9],
                    'attendees' => $o[10],
                    'requestedBudget' => $o[11],
                    'allocatedBudget' => $o[12],
                    'illustrationPath' => $o[13],
                    'creationDate' => $o[14],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'id',
                'name',
                'requested_budget',
                'allocated_budget',
                'illustration_path',
                'creation_date',
                'status',
                'requester',
                'approver',
                'attendees',
                'requestedBudget',
                'allocatedBudget',
                'illustrationPath',
                'creationDate',
            ],
        ],
    ],
    $o[0],
    []
); } },
1 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'App\\Entity\\ProjectStatus',
            ],
            'attributesMetadata' => [
                [
                    'id' => $o[1],
                    'status_name' => $o[2],
                    'creation_date' => $o[3],
                    'validated' => $o[4],
                    'projects' => $o[5],
                    'statusName' => $o[6],
                    'creationDate' => $o[7],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'id',
                'status_name',
                'creation_date',
                'validated',
                'projects',
                'statusName',
                'creationDate',
            ],
        ],
    ],
    $o[0],
    []
); } },
2 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'App\\Entity\\Users',
            ],
            'attributesMetadata' => [
                [
                    'id' => $o[1],
                    'username' => $o[2],
                    'last_name' => $o[3],
                    'first_name' => $o[4],
                    'token' => $o[5],
                    'token_date' => $o[6],
                    'email' => $o[7],
                    'password_hash' => $o[8],
                    'email_confirmed' => $o[9],
                    'terms_accepted' => $o[10],
                    'creation_date' => $o[11],
                    'user_type' => $o[12],
                    'lastName' => $o[13],
                    'firstName' => $o[14],
                    'tokenDate' => $o[15],
                    'passwordHash' => $o[16],
                    'emailConfirmed' => $o[17],
                    'termsAccepted' => $o[18],
                    'creationDate' => $o[19],
                    'userType' => $o[20],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'id',
                'username',
                'last_name',
                'first_name',
                'token',
                'token_date',
                'email',
                'password_hash',
                'email_confirmed',
                'terms_accepted',
                'creation_date',
                'user_type',
                'lastName',
                'firstName',
                'tokenDate',
                'passwordHash',
                'emailConfirmed',
                'termsAccepted',
                'creationDate',
                'userType',
            ],
        ],
    ],
    $o[0],
    []
); } },
3 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'App\\Entity\\UserTypes',
            ],
            'attributesMetadata' => [
                [
                    'id' => $o[1],
                    'name' => $o[2],
                    'creation_date' => $o[3],
                    'canAcceptProject' => $o[4],
                    'users' => $o[5],
                    'creationDate' => $o[6],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'id',
                'name',
                'creation_date',
                'canAcceptProject',
                'users',
                'creationDate',
            ],
        ],
    ],
    $o[0],
    []
); } },

]];
